#+TITLE: linux中网络相关的那些配置文件
#+AUTHOR: lujun9972
#+TAGS: linux和它的小伙伴
#+DATE: [2018-09-16 日 22:15]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* /etc/networks
机器所连接的网络中那些可以访问的网络名和网络地址

* /etc/protocols
列举了当前可用的协议名称

* /etc/resolv.conf
DNS服务器信息

#+BEGIN_SRC conf
  search domainname.com
  nameserver 192.168.1.2
  nameserver 8.8.8.8
#+END_SRC

其中 =search domainname.com= 表示当提供一个不包含完全域名的主机时，在该主机名后添加 =domainname.com= 的后缀

=nameserver xx.xx.xx.xx= 表示解析域名时使用 =xx.xx.xx.xx= 作为DNS服务器.
域名按照 =nameserver= 中指定的顺序来进行查询的。

* /etc/services
列举服务器名称对应的端口号和协议

* /etc/xinetd.conf
xinetd的配置文件，其中包含网络服务的相关信息。 目前似乎用的比较少了

需要注意的是，若在 =/etc/services= 中将服务注释掉，则即使相应的网络服务启动，也是不可用的

* /etc/hostname
包含了系统的主机名，包括完整的域名

* /etc/host.conf
指定如何解析主机名

#+BEGIN_SRC conf
  order bind,hosts
  multi on
  nospoof on
#+END_SRC

其中:

+ =order bind,hosts= 指定文件名查询顺序为先使用DNS解析域名，然后再查询 =/etc/hosts= 文件
+ =multi on= 指定 =/etc/hosts= 文件中指定的主机是否可以有多个IP地址
+ =nospoof on= 指不允许对该服务器进行IP地址欺骗。

* /etc/sysconfig/network
用来指定服务器上网络配置信息
#+BEGIN_SRC conf
  NETWORK=yes
  FORWARD_IPV4=yes
  hostname=hostname.domain.name
  GATEWAY=0.0.0.0
  GATEWAYDEV=enp0s3
#+END_SRC

其中:

+ NETWORK :: 网络是否被配置
+ FORWARD_IPV4 :: 是否开启IPV4的转发功能
+ hostname :: 服务器主机名
+ GATEWAY :: 网络网关的IP地址
+ GATEWAYDEV :: 网络的设备名
* /etc/sysconfig/network-scripts/if*
REDHAT的网络配置脚本

#+BEGIN_SRC shell :results org :dir /ssh:root@192.168.1.38:
  cat /etc/sysconfig/network-scripts/ifcfg-enp0s3
#+END_SRC

#+BEGIN_SRC org
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=dhcp
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=enp0s3
UUID=eadb9827-37e2-468a-9129-8a0b9810c08a
DEVICE=enp0s3
ONBOOT=yes
#+END_SRC

* /etc/hosts
主机与IP的对应关系
