#+TITLE: xterm使用简介
#+AUTHOR: Administrator
#+CATEGORY: linux
#+DATE: [2016-11-16 周三 19:45]
#+OPTIONS: ^:{}

* 正确显示中文

使用 =-fn= 选项可以设置xterm中以何种字体显示内容.

或者在 =.Xdefaults= 文件中加入
#+BEGIN_SRC conf-xdefaults
  XTerm*Font:       7x13
#+END_SRC

* 滚动栏

使用 =-sb= 选项可以让xterm显示出滚动条.

或者在 =.Xdefaults= 文件中加入
#+BEGIN_SRC conf-xdefaults
  XTerm*scrollBar:  true
#+END_SRC

你会在滚动条上看到一块小小的深色区域,它的大小代表你目前可以看到多少输出的部分,而它的位置指示了你现在所在的位置.

然而当你尝试用鼠标左键点击这块深色区域向上拉动时,会发现xterm中的内容毫无变化......

xterm中的滚动方式跟其他程序中用滚动条拉动滚动的方式是不同的:

若你想要向上滚动,则需要在滚动条上按下 *鼠标右键* 来完成,而且滚动的幅度随着鼠标在滚动条的位置不同而不同.

1. 若在滚动条的底部区域按下,则一次滚动一页
2. 若在滚动条的顶部区域按下,则一次滚动一行
3. 若在滚动条中间区域按下,则一次滚动半页

而若你想要向下滚动的话,则只需要改成在滚动条上按下 *鼠标左键* 即可.

* 保存当前XTerm的配置

* 复制与粘贴

只要按下鼠标并拖拽鼠标选中要复制的内容就完成复制操作了.

如果要调整选中的区域,可以按住Shift键,然后拖拽鼠标左键进行调整.

如果你想要复制整个单词,那么只需要双击一下鼠标就会发现xterm帮你选中了整个单词.

类似的,如果你想要复制的是整个行,那么只需要三击一下鼠标就会发现xterm帮你选中了整行的内容.

在xterm按下鼠标中键就能完成粘贴操作了.

* log文件

* xterm菜单

* xterm其他参数说明

** -ls选项
ls是login shell的意思,若带此选项运行xterm,则xterm会加载你的~/.bash_profile(bash shell),或者你的~/.login文件(c shell)


   
