#+TITLE:       提交github后自动完成habitica habit
#+AUTHOR:      lujun9972
#+EMAIL:       lujun9972@lujun9972-desktop
#+DATE:        2016-11-01 二

#+URI:         /时间管理/%y/%m/%d/%t/ Or /时间管理/%t/
#+TAGS:        github, habitica, GTD
#+DESCRIPTION: 提交github后自动完成habitica habit

#+LANGUAGE:    zh-CN
#+OPTIONS:     H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* 什么是Habitica
[[https://habitica.com][Habitica]] 是一个款超赞的游戏化软件，它致力于帮助用户培养习惯和提高效率。
与传统的效率类软件不同的是，Habitica使生活看起来就像一场复古的像素风角色扮演游戏。

在Habitica中,任务被分成了三种类别：

+ 习惯 :: 该栏目主要用于添加一些非日常，没有规律性但具有持续性的任务
+ 每日任务 :: 该栏目主要用于添加一些自己决定每日必做的日常任务。
+ 待办事项 :: 该栏目用于添加一些一次性，有时限的任务，很适合用于备忘。

为了激励我维护github上的repo，我将那些需要长期维护的repo都做成了habitica里面的habit了。
但是每次我提交github都要手工在Habitica上点击一次完成habit明显太麻烦了。
不过借助[[https://github.com/nasfarley88/habash][habash]] 与 [[https://travis-ci.org/][travis-ci]] 很容易就能做到这一点。

* Habash介绍
habash是一款由shell实现的habitica api，它的用法也很简单，只需要：

1. 设置好环境变量 =HABITICA_TOKEN= 与 =HABITICA_UUID=

2. 运行 =habash up habit任务描述= 就能标记一个habit已完成了
   
* 结合Habash与Travis-ci自动完成habit
travis-ci能让我们在每次提交github后自动触发执行一段脚本。 所以我们只需要让travis-ci帮我们自动调用habash来完成任务就行了。 

整个过程非常的简单:

1. 在要监控的github repo上添加一个 =.travis.yml= 文件，录入下面内容
   #+BEGIN_SRC yaml
     language: generic
     sudo: false

     branches:
       only:
         - master
         - source
         # 这里可以添加你要监控哪些branch

     before_install:
      - git clone https://github.com/nasfarley88/habash

     script:
     - ./habash/habash up "<你自己的Habit任务描述>"
   #+END_SRC
   
2. 用github用户登陆 [[https://travis-ci.org/][travis-ci]]

3. 在travis-ci上启用要监控的github repo

4. 在项目的Settings中可以配置环境变量，我们配置好 =HABITICA_TOKEN= 与 =HABITICA_UUID= 这两个环境变量后就行了
