#+TITLE: init-misc-symon
#+AUTHOR: DarkSun
#+DATE: [2015-05-07 星期四 16:10]
#+OPTIONS: ^:{}
* 加载symon
#+BEGIN_SRC emacs-lisp
  (require-and-install 'symon)
#+END_SRC
* 配置
+ symon-monitors
  监控那些系统状态的列表

  - symon-linux-memory-monitor
    memory usage (%) and swapped memory (MB) via /proc/meminfo

  - symon-linux-cpu-monitor
    CPU load (%) via /proc/stat

  - symon-linux-battery-monitor
    remaining battery (%) via built-in library battery.el

  - symon-linux-network-rx-monitor
    network RX (KB/s) via /proc/net/dev

  - symon-linux-network-tx-monitor
    network TX (KB/s) via /proc/net/dev

  - symon-darwin-memory-monitor
    memory usage (%) and swapped memory (MB) via sysctl

  - symon-darwin-cpu-monitor
    CPU load (%) via hostinfo

  - symon-darwin-battery-monitor
    remaining battery (%) via built-in library battery.el

  - symon-darwin-network-rx-monitor
    network RX (KB/s) via netstat

  - symon-darwin-network-tx-monitor
    network TX (KB/s) via netstat

  - symon-windows-memory-monitor
    memory usage (%) via WMI

  - symon-windows-page-file-monitor
    page file usage (MB) via WMI

  - symon-windows-cpu-monitor
    CPU load (%) via WMI

  - symon-windows-battery-monitor
    remaining battery (%) via WMI

  - symon-windows-network-rx-monitor
    network RX (KB/s) via WMI

  - symon-windows-network-tx-monitor
    network TX (KB/s) via WMI

  - symon-current-time-monitor
    current Time (hh::mm) via built-in function format-time-stirng 
    
+ symon-refresh-rate
    Refresh rate of symon display.
+ symon-delay
    Delay in seconds until symon is displayed.
+ symon-history-size
    Number of old values to keep. Sparklines grow faster when set smaller.

You need to restart symon-mode in order to reflect changes of these 4 options above.

+ symon-sparkline-height
    Height of sparklines.
+ symon-sparkline-width
    Width of sparklines.
+ symon-sparkline-thickness
    Line width of sparklines.
+ symon-sparkline-ascent
    Adjust vertical position of sparklines.
+ symon-sparkline-type
  Type of sparklines. following preconfigured types are available:
  #+BEGIN_SRC emacs-lisp
  (setq symon-sparkline-type 'plain)
  #+END_SRC

  - plain

  - bounded

  - boxed

  - gridded
    
