#+TITLE: mobileog 手机端同步提示Error:2 No such file 的解决方法
#+AUTHOR: lujun9972
#+TAGS: Emacs之怒
#+DATE: [2023-11-24 Fri 10:30]
#+LANGUAGE:  zh-CN
#+STARTUP:  inlineimages
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
#+filetags: :GTD,:mobile_phone,:org_mode,:Emacs:article:

* 现象
在 mobileorg 手机端同步时，报错 "Error:2 No such file". 但是服务器端的 index.org 文件明明是存在的。
且在 "Setup Wizard" 中 "检查 SSH 登陆" 是成功的。

* 解决方案

在 "Setup Wizard" 中 "检查 SSH 登陆" 成功则能说明 index.org 的路径配置正确且文件确实存在。
如果还是提示 "Error:2 No such file" 那么说明是文件格式有问题

根据  [[https://mobileorg.github.io/documentation/][MobileOrg Documentation]] 中“What files are transferred?”的描述：
1. mobileorg 除了会下载 index.org 之外，还会解析该文件并将其他相关的 org 文件一同下载下来。
2. 为了防止重复下载，mobileorg 通过在 checksums.dat 中存储各个 org 文件的 hash 值的方式来决定哪些 org 文件需要被下载下来。
   即只有 hash 值发生改变的 org 文件才会被下载。

这里，比较常见的问题是手工生成空的 index.org, 结果导致由于无法正常解析 index.org 中的内容而提示同步失败。正确的做法是通过运行 Emacs 的 [[help:org-mobile-push][org-mobile-push]] 函数来生成 index.org 文件（需要提前配置好 [[help:org-mobile-directory][org-mobile-directory]] 和 [[help:org-mobile-inbox-for-pull][org-mobile-inbox-for-pull]] 变量）。

另一个比较常见的问题就是 org 文件名中带空格（比如当将 mobileorg 与 orgzly 联用时 orgzly 自带的帮助文档就带有空格），mobileorg 手机端应用似乎对带空格的文件名没有处理好。
解决方法就是去掉文件名中的空格，然后重新运行 [[help:org-mobile-push][org-mobile-push]] 函数来生成新的 index.org 与 checksums.dat 文件 

* 参考
+ [[https://superuser.com/questions/645079/mobileorg-not-finding-emacs-org-file-with-ssh-server][MobileOrg not finding Emacs org file with ssh server]]
+ [[https://mobileorg.github.io/documentation/][MobileOrg Documentation]]
