#+TITLE: Some Things That Have Helped Me Worry Less
#+AUTHOR: lujun9972
#+TAGS: Scott H Young的订阅
#+DATE: [2019-05-15 三 19:13]
#+LANGUAGE:  zh-CN
#+STARTUP:  inlineimages
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

1. 不要试图控制自己的想法

   想法来自于大脑深处，你无法像控制“看”、“听”、“触摸”等感知器官这样来控制自己的想法。
   
   我们可能会试图强迫自己不要想太多,或者努力让自己想出一个解决之道来，但常常适得其反,只是让自己变得更加焦虑而已.
   但是有些焦虑根本是庸人自扰，过一阵子就会忘掉的，那不妨考虑第三条路: =什么也不管=

2. 脱离社交媒体

   社交媒体是焦虑的一大来源，试着关闭那些跟你带来焦虑感的信息来源。

3. 直面那些一再出现的焦虑
   
   直面你的焦虑，它们往往没有你想象的那么严重

4. 不要去尝试缓解焦虑

   人们常犯的一个错误就是为了缓解焦虑而去寻找安慰。这会让你在短期内好受一点，但是长期来看会让情况变得更糟糕。
   因为心理学上有一个模型是说:

   #+BEGIN_SRC org
     焦虑是带有明确的目的性动机。其目的就是要识别威胁并制定解决办法。
     当我们通过安慰让自己好受一点的时候，我们是在通过[[https://p.feedblitz.com/t3.asp?/194079/35570923/6518537_/~en.wikipedia.org/wiki/Reinforcement#Negative_reinforcement][负强化]]强化这一行为模式，
   #+END_SRC

5. 问问自己会因为这种焦虑而做出什么行为改变吗

   当焦虑无法改变你的行为时，那它就是无用的，不管它有多合理。

   
* 原文
I worry about things more than I’d like to.

I worry about making mistakes, getting criticized, having my business fail, being awkward or rude in social situations and lots of other things.

Most of the time my worries just stay in my head. They’re there, but I ignore them well enough to get on with my day and keep working.

Other times, those worries grip me and derail my progress. I struggled immensely with big parts of writing my upcoming book. My own expectations (and imagined attacks) made starting the writing portion of each chapter a strenuous chore.

I don’t think my level of anxiety is unusual or extreme. I don’t get panic attacks, and I haven’t had anxiety debilitate my life the way it does for many. That said, I’ve tried a lot of things to make it easier. Here’s what’s worked for me.

** Things I’ve Done to Worry Less

 Most problems in life are stubborn, rather than complicated. Thus we tend to spend our lives fighting against the same problems over and over. Progress is possible, but at the same time, our old foes are rarely completely vanquished.

 Overcoming worrying isn’t a trivial issue. But it there are strategies you can use to lessen the impact.

*** 1. Don’t Own Your Thoughts

 I’ve found meditation helpful, not so much for the actual meditation itself, but for the idea of what meditation tries to accomplish and to apply the same abstract principles to my ordinary life.

 One of the core ideas of Buddhist philosophy is anatman, or not-self. The idea essentially boils down to reviewing everything in your conscious experience and recognizing that you don’t have control over it.

 It’s easy to see your thoughts as part of yourself. Something you create and control. It can therefore be frustrating when you can’t help yourself from worrying.

 Another way of looking at it, however, is that thoughts just happen. They are a sensory experience, not part of you. Thoughts comes from inside your head, but otherwise they’re as much under your control as what you see, hear or feel from the outside world.

 Denying ownership of a thought gives you a choice not to grab onto it. Just like how you might have an annoying sound in the background and choose to ignore it because there’s nothing you can do, you can similarly have a distracting, negative thought and choose to do nothing about it.

 This approach is different because most of us spend our time trying to “stop” ourselves from worrying (which makes it worse), or try to “solve” the worry by imagining a way to avoid the threat. It’s easy to forget that there’s a third option: do nothing.

*** 2. Get Off Social Media.

 Facing down your fears is good. But there’s a difference between healthy exposure to things that give you anxiety, and indulging in a non-stop download of algorithmically-optimized information designed to trigger your threat response.

 Twitter is my vice of choice. I love being able to engage with smart people from around the world on interesting topics. More than once I’ve learned fascinating new things. But the platform is also a nightmare for throwing up things that make you feel angry or anxious.

 I now believe that resiliency must be matched with choosing appropriate environments. Mute the people and sources that make you feel worried. Especially if those are the people on “your side.”

*** 3. Identify Your Acute Anxieties, Face Them Head-On.

 Not all anxieties are recurring. You may worry that you said something weird to that person one time, and forget about it a few days later. Others, however, have consistent themes and show up again and again.

 One of mine is definitely being criticized for my work or projects. Over the last thirteen years I’ve said and done a lot. A lot of the things I’ve said or decisions I made have probably been wrong. Thus, anyone with an axe to grind against me would have plenty of material to make an attack.

 This worry has often been stoked by seeing highly-public cases of someone having their career ruined because of a relatively innocent mistake. I remember puzzling over the downfall of Jonah Lehrer, whose sky-rocketing writing career was torn down over misquoting Bob Dylan. I agree he made some mistakes, but the punishment didn’t match the crime.

 Although I can’t simulate a career-ending mistake without making one, I’ve tried to attenuate my own fears of criticism by going out and reading it. When I do, the attacks are rarely as bad as the ones I imagine. Even from people who hate me (one guy even created a website saying why he hated me), the reality is usually easier than my imagination.

 Your fears may be different. It might be failing a big test, getting fired or being humiliated. Seeking mild exposure to those things you fear is often the only way to diminish their intensity.

*** 4. Stop Trying to Solve It.

 My friend, a clinical psychologist, told me that one of the big mistakes people make to deal with anxiety is seeking reassurance. You worry, so naturally you want to talk to someone who will tell you everything will be okay.

 While this does make you feel better for a short time, it actually makes it worse later. By “rewarding” your anxious mental patterns with reassurance, you strengthen this pattern of behavior through negative reinforcement.

 Similarly, you can have the same issue when trying to “solve” your worries. If you’re have anxious thoughts about someone humiliating you at work, you might fantasize your comeback.

 The alternative approach, suggested by my friend, was to resist the temptation to find a way out of your problem. It will make your anxiety worse, but because there’s no “resolution”, the pattern that led to your anxiety is reduced.

 This model suggests that anxiety is a motivation with a clear purpose. That purpose is to identify threats and formulate solutions to them. When the goal of this feeling is frustrated, the response is weakened for the next time.

** Ask if a Worry is Actionable, Not Rational

 I got an email from a reader who also struggles with anxiety, and said that although he can see from a distant perspective that many of his anxieties are irrational, he can’t so easily separate the legitimate worries from the ridiculous ones when they’re afflicting him.

 A behavior that is bad 100% of the time is much easier to break off as a habit than one which is beneficial some of the time. When you quit smoking, you can go cold turkey. When you want to quit overeating, you can’t stop eating food. Similarly, some anxiety is probably a good thing. But too much can be crippling.

 What this reader wanted to be able to do was to figure out which fears were rational and which were not, in the moment, so as to ignore the irrational ones.

 *You can’t separate out the “rational” worries from the irrational ones.*

 Most of your anxieties, even the ones you should have less of, do have a rational basis. The things I fear are not things that are totally without merit, although I should probably worry about them less than I do typically.

 Instead of asking whether something is irrational, ask if you should change your behavior. When a worry can’t change your response, it’s not helpful, even if it might be rational.

 The post Some Things That Have Helped Me Worry Less appeared first on Scott H Young.
