name: 提交 habitica 任务
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out bahash code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: nasfarley88/habash
      - name: 提交 habitica 任务
        run: ./habash up "写博客"
